const questions = {
  question1: {
    question: "Test 1",
    button1: { text: "answer 1", points: 4 },
    button2: { text: "answer 2", points: 3 },
    button3: { text: "answer 3", points: 2 },
    button4: { text: "answer 4", points: 1 },
  },
  question2: {
    question: "Test 2",
    button1: { text: "answer 1", points: 4 },
    button2: { text: "answer 2", points: 3 },
    button3: { text: "answer 3", points: 2 },
    button4: { text: "answer 4", points: 1 },
  },
  question3: {
    question: "Test 3",
    button1: { text: "answer 1", points: 4 },
    button2: { text: "answer 2", points: 3 },
    button3: { text: "answer 3", points: 2 },
    button4: { text: "answer 4", points: 1 },
  },
  question4: {
    question: "Test 4",
    button1: { text: "answer 1", points: 4 },
    button2: { text: "answer 2", points: 3 },
    button3: { text: "answer 3", points: 2 },
    button4: { text: "answer 4", points: 1 },
  },
  question5: {
    question: "Test 5",
    button1: { text: "answer 1", points: 4 },
    button2: { text: "answer 2", points: 3 },
    button3: { text: "answer 3", points: 2 },
    button4: { text: "answer 4", points: 1 },
  },
  question6: {
    question: "Test 6",
    button1: { text: "answer 1", points: 4 },
    button2: { text: "answer 2", points: 3 },
    button3: { text: "answer 3", points: 2 },
    button4: { text: "answer 4", points: 1 },
  },
  question7: {
    question: "Test 7",
    button1: { text: "answer 1", points: 4 },
    button2: { text: "answer 2", points: 3 },
    button3: { text: "answer 3", points: 2 },
    button4: { text: "answer 4", points: 1 },
  },
  question8: {
    question: "Test 8",
    button1: { text: "answer 1", points: 4 },
    button2: { text: "answer 2", points: 3 },
    button3: { text: "answer 3", points: 2 },
    button4: { text: "answer 4", points: 1 },
  },
  question9: {
    question: "Test 9",
    button1: { text: "answer 1", points: 4 },
    button2: { text: "answer 2", points: 3 },
    button3: { text: "answer 3", points: 2 },
    button4: { text: "answer 4", points: 1 },
  },
  question10: {
    question: "Test 10",
    button1: { text: "answer 1", points: 4 },
    button2: { text: "answer 2", points: 3 },
    button3: { text: "answer 3", points: 2 },
    button4: { text: "answer 4", points: 1 },
  },
};
